spring:
  data:
    mongodb:
      port: 0
      database: library


mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.cherry.springhomework.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local


